### ISSUE TITLE
Installing on Mac OS Big Sur

### ISSUE THREAD

**Issue by alraben** [seanharr11/etlalchemy#55]
Hi,

I have problem installing it on Big Sur.

pip3  install etlalchemy

python3 migration.py

and I have the following error:

Traceback (most recent call last):
  File "migration.py", line 1, in <module>
    from etlalchemy import ETLAlchemySource, ETLAlchemyTarget
  File "/Users/alraben/Library/Python/3.8/lib/python/site-packages/etlalchemy/__init__.py", line 1, in <module>
    from ETLAlchemySource import ETLAlchemySource
ModuleNotFoundError: No module named 'ETLAlchemySource'

Can somebody help me?

thanks

**Comment by pkej** [comment]
I had to use python2.7. I rolled a dockerfile and published it on my github. Take a look there if you didn't abandon this already and found another method.
